name: pytorch_new
channels:
  - pytorch
  - conda-forge
  - nvidia
  - anaconda
  - defaults
dependencies:
  - absl-py=2.1.0=py310haa95532_0
  - arrow-cpp=19.0.0=h33d5241_1
  - asttokens=3.0.0=py310haa95532_0
  - async-timeout=5.0.1=py310haa95532_0
  - aws-c-auth=0.6.19=h2bbff1b_0
  - aws-c-cal=0.5.20=h2bbff1b_0
  - aws-c-common=0.8.5=h2bbff1b_0
  - aws-c-compression=0.2.16=h2bbff1b_0
  - aws-c-event-stream=0.2.15=hd77b12b_0
  - aws-c-http=0.6.25=h2bbff1b_0
  - aws-c-io=0.13.10=h2bbff1b_0
  - aws-c-mqtt=0.7.13=h2bbff1b_0
  - aws-c-s3=0.1.51=h2bbff1b_0
  - aws-c-sdkutils=0.1.6=h2bbff1b_0
  - aws-checksums=0.1.13=h2bbff1b_0
  - aws-crt-cpp=0.18.16=hd77b12b_0
  - aws-sdk-cpp=1.11.212=h6a15179_0
  - blas=1.0=mkl
  - blinker=1.9.0=py310haa95532_0
  - boost-cpp=1.82.0=h59b6b97_2
  - bottleneck=1.4.2=py310hc99e966_0
  - brotli-python=1.0.9=py310h5da7b33_9
  - brotlicffi=1.0.9.2=py310h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.19.1=h2bbff1b_0
  - ca-certificates=2025.9.9=haa95532_0
  - cairo=1.16.0=h85cdd14_6
  - certifi=2025.10.5=py310haa95532_0
  - cffi=1.17.1=py310h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.8=py310haa95532_0
  - colorama=0.4.6=py310haa95532_0
  - comm=0.2.1=py310haa95532_0
  - contourpy=1.3.1=py310h214f63a_0
  - cuda-cccl=12.4.127=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.4.127=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.8.0=hd77b12b_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - datasets=2.12.0=py310haa95532_0
  - debugpy=1.8.11=py310h5da7b33_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dill=0.3.6=py310haa95532_0
  - eigen=3.4.0=h59b6b97_0
  - et_xmlfile=2.0.0=py310haa95532_0
  - exceptiongroup=1.2.0=py310haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h8ddb27b_0
  - ffmpeg=4.3.1=ha925a31_0
  - filelock=3.17.0=py310haa95532_0
  - flask=3.1.0=py310haa95532_0
  - fontconfig=2.14.1=hb33846d_3
  - fonttools=4.55.3=py310h827c3e9_0
  - freetype=2.13.3=h0620614_0
  - fsspec=2025.7.0=py310hbc747e5_0
  - gflags=2.2.2=hd77b12b_1
  - giflib=5.2.2=h7edc060_0
  - glog=0.5.0=hd77b12b_1
  - glpk=4.65=h2bbff1b_3
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py310h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - grpcio=1.62.2=py310h5da7b33_0
  - gst-plugins-base=1.22.3=hfc3ed34_1
  - gstreamer=1.22.3=h1779075_1
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - huggingface_hub=0.31.2=py310haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py310haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py310haa95532_1
  - ipython=8.30.0=py310haa95532_0
  - itsdangerous=2.2.0=py310haa95532_0
  - jedi=0.19.2=py310haa95532_0
  - jinja2=3.1.6=py310haa95532_0
  - joblib=1.4.2=py310haa95532_0
  - jpeg=9e=h827c3e9_3
  - jupyter_client=8.6.3=py310haa95532_0
  - jupyter_core=5.8.1=py310haa95532_0
  - kiwisolver=1.4.8=py310h5da7b33_0
  - krb5=1.20.1=h5b6d351_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libabseil=20240116.2=cxx17_he0c23c2_1
  - libboost=1.82.0=h3399ecb_2
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libclang=14.0.6=default_hb5a9fac_2
  - libclang13=14.0.6=default_h8e68704_2
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.14.1=ha9f67de_0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_1
  - libevent=2.1.12=h56d1f94_1
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.2=h405b238_0
  - libgrpc=1.62.2=hf25190f_0
  - libiconv=1.16=h2bbff1b_3
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libogg=1.3.5=h2bbff1b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h70ee33d_0
  - libprotobuf=4.25.3=hf2fb9eb_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=h4364b78_2
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libvorbis=1.3.7=he774522_0
  - libwebp=1.3.2=hbc33d0d_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown=3.8=py310haa95532_0
  - markupsafe=3.0.2=py310h38315fa_1
  - matplotlib-base=3.10.0=py310he19b0ae_0
  - matplotlib-inline=0.1.6=py310haa95532_0
  - mizani=0.13.1=py310haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py310h827c3e9_2
  - mkl_fft=1.3.11=py310h827c3e9_0
  - mkl_random=1.2.8=py310hc64d2fc_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py310haa95532_0
  - multiprocess=0.70.14=py310haa95532_0
  - nest-asyncio=1.6.0=py310haa95532_0
  - networkx=3.4.2=py310haa95532_0
  - numexpr=2.11.0=py310hdb065b2_0
  - numpy=1.26.4=py310h055cbcc_0
  - numpy-base=1.26.4=py310h65a83cf_0
  - opencv=4.10.0=py310h4e21365_2
  - openjpeg=2.5.2=hae555c5_0
  - openpyxl=3.1.5=py310h827c3e9_1
  - openssl=3.5.1=h725018a_0
  - orc=2.0.1=hd8d391b_0
  - packaging=24.2=py310haa95532_0
  - pandas=2.2.3=py310h5da7b33_0
  - parso=0.8.4=py310haa95532_0
  - patsy=1.0.1=py310haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pillow=11.1.0=py310h096bfcc_0
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h2bbff1b_1
  - platformdirs=4.3.7=py310haa95532_0
  - plotnine=0.14.5=py310haa95532_0
  - prompt-toolkit=3.0.43=py310haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - protobuf=4.25.3=py310hf91db99_1
  - psutil=5.9.0=py310h827c3e9_1
  - pulp=3.2.2=py310h46a8372_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=19.0.0=py310h5da7b33_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=py310haa95532_0
  - pyparsing=3.2.0=py310haa95532_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.18=h981015d_0
  - python-dateutil=2.9.0post0=py310haa95532_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py310h827c3e9_0
  - python_abi=3.10=2_cp310
  - pytorch=2.5.1=py3.10_cuda11.8_cudnn9_0
  - pytorch-cuda=11.8=h24eeafa_6
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=py310haa95532_0
  - pywin32=308=py310h5da7b33_0
  - pyyaml=6.0.2=py310h827c3e9_0
  - pyzmq=26.2.0=py310h5da7b33_0
  - qt-main=5.15.2=h19c9488_12
  - re2=2022.04.01=hd77b12b_0
  - requests=2.32.4=py310haa95532_0
  - responses=0.13.3=pyhd3eb1b0_0
  - safetensors=0.5.3=py310haa69e8e_0
  - scikit-learn=1.6.1=py310h585ebfc_0
  - scipy=1.15.3=py310h180bac5_0
  - seaborn=0.13.2=py310haa95532_3
  - sentence-transformers=4.1.0=py310haa95532_0
  - setuptools=78.1.1=py310haa95532_0
  - six=1.17.0=py310haa95532_0
  - snappy=1.2.1=hcdb6601_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.5=py310hf9130e5_0
  - tbb=2021.8.0=h59b6b97_0
  - tensorboard=2.19.0=py310haa95532_0
  - tensorboard-data-server=0.7.0=py310haa95532_1
  - threadpoolctl=3.5.0=py310h9909e9c_0
  - tk=8.6.14=h5e9d12e_1
  - torchtext=0.6.0=py_1
  - tornado=6.5.1=py310h827c3e9_0
  - tqdm=4.67.1=py310h9909e9c_0
  - traitlets=5.14.3=py310haa95532_0
  - typing-extensions=4.12.2=py310haa95532_0
  - typing_extensions=4.12.2=py310haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - unicodedata2=15.1.0=py310h827c3e9_1
  - urllib3=2.5.0=py310haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=py310haa95532_0
  - werkzeug=3.1.3=py310haa95532_0
  - wheel=0.45.1=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xxhash=0.8.0=h2bbff1b_3
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.2.13=h8cc25b3_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - accelerate==0.26.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - attrs==25.3.0
      - frozenlist==1.7.0
      - huggingface-hub==0.34.3
      - hugsvision==0.75.5
      - lightning-utilities==0.15.0
      - multidict==6.6.3
      - propcache==0.3.2
      - pyaml==25.7.0
      - pycocotools==2.0.10
      - pytorch-lightning==2.5.2
      - regex==2025.7.31
      - scikit-optimize==0.10.2
      - sko==0.5.7
      - sympy==1.13.1
      - tabulate==0.9.0
      - timm==1.0.19
      - tokenizers==0.21.4
      - torchaudio==2.5.1
      - torchmetrics==1.8.0
      - torchsummary==1.5.1
      - torchvision==0.20.1
      - transformers==4.54.1
      - yarl==1.20.1
prefix: E:\Anaconda\anaconda\envs\pytorch_new
